# Generated by Django 3.1.7 on 2021-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taplink',
            name='avatar',
            field=models.ImageField(upload_to='image', verbose_name='Фото'),
        ),
    ]
