# Generated by Django 3.1.7 on 2021-04-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0002_auto_20210425_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messanger',
            new_name='Messenger',
        ),
    ]
