# Generated by Django 3.1.7 on 2021-04-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0003_auto_20210425_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='headline',
            field=models.CharField(default='Заголовок', max_length=70, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
