# Generated by Django 3.1.7 on 2021-04-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0004_auto_20210426_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='headline',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taplink_texts', to='taplink.taplink', verbose_name='Привязанный таплинк'), max_length=70, verbose_name='Заголовок'),
        ),
    ]
