# Generated by Django 3.1.7 on 2021-04-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taplink', '0006_auto_20210427_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='telegram',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Ссылка на телеграм'),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Ссылка на ватсапп'),
        ),
        migrations.AlterField(
            model_name='taplink',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='taplink',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='taplink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taplink', to=settings.AUTH_USER_MODEL),
        ),
    ]
