# Generated by Django 3.1.7 on 2021-05-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0009_auto_20210506_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taplinktext',
            name='headline',
        ),
    ]
