# Generated by Django 3.1.7 on 2021-05-24 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0010_remove_taplinktext_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taplink',
            name='slug',
            field=models.SlugField(blank=True, default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taplink', to=settings.AUTH_USER_MODEL), verbose_name='Ссылка'),
        ),
    ]
