# Generated by Django 3.1.7 on 2021-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0012_auto_20210524_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taplink',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Ссылка'),
        ),
    ]
