# Generated by Django 3.1.7 on 2021-06-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0014_auto_20210602_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
