# Generated by Django 3.1.7 on 2021-04-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210413_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
