# Generated by Django 3.1.7 on 2021-04-15 07:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210413_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
