# Generated by Django 3.1.7 on 2021-05-14 16:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210514_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
